
-- mkrxs for rx18

local util = require "util"
local strf = string.format

-- append conf

local confname = arg[1]

if not confname then 
	print("Usage:  mkrxs confname    (eg.  mkrxs test)")
	os.exit(1)
end

local conf = assert(util.fget(confname .. ".conf"))

local st = { "--  DO NOT EDIT THIS FILE  --", conf }


-- append modules

local ml = {
	"util",
	"ssock",
	"rx",
}

local fmtmod = 
[[
-- #####################################################################
-- module:  %s

package.preload[%q] = function()
%s
end --module: %s

]]

local m, mf, name

-- append modules

for i, name in ipairs(ml) do
	m = util.fget(name .. ".lua")
	mf = strf(fmtmod, name, name, m, name)
	table.insert(st, mf)
end

-- append main

local main = [[

-- #####################################################################
-- main:   rxs

local rx = require"rx"
rx.runserver()

]]

table.insert(st, main)
local s = table.concat(st, "\n\n")

local outname = "rxs-" .. confname .. ".lua"
util.fput(outname, s)

print("rx server stored in:", outname)

	
	
	
	
	
	