name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run citest.lua
      run: |
        # get he, slua; slua citest.lua
        # set -x
        set -v
        uname -a
        wget -q https://github.com/philanc/he/archive/master.zip
        unzip -j master.zip he-master/he.lua
        wget -q -O slua https://github.com/philanc/slua/raw/master/bin/slua
        chmod ugo+x ./slua
        ./slua citest.lua
        #ls -la

        
